### ISSUE TITLE
Log an error if non-durable messages are found

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.AzureStorageQueues#168]
Connects to issue https://github.com/Particular/docs.particular.net/issues/2172.
ASQ doesn't support non-durable messages and `Express` attribute is silently ignored providing no indication to users.

Connects to https://github.com/Particular/NServiceBus.Azure/issues/309

**Comment by Scooletz** [comment]
@SimonCropp I've read the doco page for `Express` messages several times and it still looks vague to me. It's possible that the reason is that it's aimed to describe an MSMQ feature as in

 ` This makes the endpoint susceptible to message loss during server crashes and restarts.`

Depending on the understanding of this we COULD somehow support similar behavior in ASQ, for instance we could dispatch messages without awaiting for the response from Azure services. Yes, if a destination queue is not configured properly that would mean dropping messages without the server restart/crash. Does it if the `Express` message description then?

What's the meaning of `Express` then? Is it worth to consider seeing this coming: https://github.com/Particular/NServiceBus/issues/4252 ?

Ping @Particular/azure-storage-queues-maintainers
