### ISSUE TITLE
CancellationToken usage in TimeoutsPoller

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.AzureStorageQueues#179]
Any reason we dont pass through the CancellationToken on these lines

 * https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/DelayDelivery/TimeoutsPoller.cs#L163
 * https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/DelayDelivery/TimeoutsPoller.cs#L170
 * ~https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/DelayDelivery/TimeoutsPoller.cs#L44~

**Comment by SimonCropp** [comment]
ping @danielmarbach

**Comment by SimonCropp** [comment]
there is also a number if nested calls from those method where we could pass the CancellationToken  in. eg we could pass it to LockManager

**Comment by danielmarbach** [comment]
@SimonCropp https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/DelayDelivery/TimeoutsPoller.cs#L44 doesn't really make sense to pass in the token. The outcome you'd achieve is the following:

When the token is cancelled the task will change into the cancelled state and when awaited while stopping rethrow the cancelled exception. Since we want graceful shutdown I'd say we don't want to pass in the token. In the other points you mentioned I'd say it should be passed in unless there are some fancy reasons why not to

**Comment by Scooletz** [comment]
@SimonCropp Could you close it if your concerns were addressed ?

**Comment by danielmarbach** [comment]
I think the other two locations need the token

**Comment by Scooletz** [comment]
Thanks @danielmarbach for clarification.
