### ISSUE TITLE
Dont override the default serializer

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.AzureStorageQueues#253]
* a transport should not have an opinion on this
* since the newtonsoft serializer is now external it meas the AzureStorageQueues nuget now has two extra dependencies. newtonsoft and NServiceBus.Newtonsoft.Json 
* when moving to the new major of AzureStorageQueues we will silently be moving them from the internal to the external json serializer. the problem is these to serializers are not 100% compatible. https://docs.particular.net/nservicebus/serialization/newtonsoft#compatibility-with-the-core-json-serializer
* makes the AzureStorageQueues nuget more prone to extra releases, since any major release of newtonsoft and NServiceBus.Newtonsoft.Json will require that the AzureStorageQueues nuget also be released
* the current "hidden + defaulted"  approach hides apis that people should be aware of and use eg https://docs.particular.net/nservicebus/serialization/newtonsoft#usage-custom-settings
* uses the non-public api of the magic key `"MainSerializer"`. this key is free to change in any patch release of the core
* prone to side effects on initialisation order. eg `AzureStorageQueueTransport` sets the main serializer and then the user sets the main serialzier on the standard endpointconfig api. I assume endpointconfig wins. but it only wins due to the initialisation order that the core uses for the transport infrastructure and the serialization definition
* uses the non-public api `SettingsHolder.Merge` via reflection. which is prone to breaking in any patch release of the core

@boblangley modified on 2017-09-15 to add POA

## POA
- [x] Transport no longer has an opinion on the serializer PR #263 
- [x] Remove dependencies on Newtonsoft/NServiceBus.Newtonsoft.Json PR #263
- [ ] Update guide for transport should address move to external serializer

**Comment by danielmarbach** [comment]
Agree with @SimonCropp on this one.

**Comment by yvesgoeleven** [comment]
> a transport should not have an opinion on this

I agree to this, but the core should neither. Currently XML is the default,  which almost always results in exceptions the first time a user tries our transport. This defaut is just there to have an F5 experience

> uses the non-public api of the magic key "MainSerializer". this key is free to change in any patch release of the core
> prone to side effects on initialisation order. eg AzureStorageQueueTransport sets the main serializer and then the user sets the main serialzier on the standard endpointconfig api. I assume endpointconfig wins. but it only wins due to the initialisation order that the core uses for the transport infrastructure and the serialization definition

This transport needs access to the serializer used by the core, as the message structure has no header concept, we need the serializer to wrap the message an amend the headers. Ideally this is done using the same serializer as the body, so that the user only needs 1 toolset to view message content.

**Comment by SimonCropp** [comment]
> I agree to this, but the core should neither. Currently XML is the default, which almost always results in exceptions the first time a user tries our transport.

agreed 100%. the core should not have a default serializer and we should do this in v7 cc @Particular/nservicebus-maintainers

**Comment by andreasohlund** [comment]
The decision was to not include this in v7 https://github.com/Particular/PlatformDevelopment/issues/1378#issuecomment-325561069

But that wouldn't block this issue in any way right?

How about checking if the MainSerializer is explicitly set https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Serialization/SerializationSettingsExtensions.cs#L39 and throw if not?

**Comment by andreasohlund** [comment]
Sorry, meant that the core will still default to xml in v7, updated my comment

**Comment by yvesgoeleven** [comment]
@andreasohlund that class is Internal, can we please get access to it?

**Comment by SeanFeldman** [comment]
We'd still be accessing internals - the key to get the serializer from `ReadOnlySettings`.

**Comment by andreasohlund** [comment]
Either that or waiting for the next major?

**Comment by danielmarbach** [comment]
I think it is OK as a temporary workaround to access the key that is internal magic of the core. The problem with the default Xml Serializer is that is it not suitable for ASQ at all. As soon as you have a few properties on the message it will start blowing up because we reach the message size limitations. In that regard picking a serializer is not a no-brainer as argued in the larger discussion around making the serializer mandatory. Probably a good and simple step to move forward is the following:

- ASQ and ASB major make the serializer mandatory. Therefore like @andreasohlund proposed will throw when the main serializer is not explicitly set. This will be implemented by accessing the main serializer key. In the next major we can then look again at the whole serializer story as outlined in https://github.com/Particular/PlatformDevelopment/issues/1378#issuecomment-325561069

One could argue due to the restrictive message size limitations XmlSerializer is pretty much a no go for any cloud transport. So does that mean we should apply the same for SQS as well? Thoughts @Particular/aws-maintainers ?

**Comment by SimonCropp** [comment]
@yvesgoeleven @SeanFeldman can u point me to where this is captured in the upgrade guide?

**Comment by SeanFeldman** [comment]
ASQ: https://docs.particular.net/transports/upgrades/asq-7to8#serialization-is-mandatory
ASB (needs to be aligned with ASB): https://docs.particular.net/transports/upgrades/asb-7to8#serialization-is-mandatory
