### ISSUE TITLE
Figure out a way to create an ATT that covers both ASP(like) timeoutmanager support with ASQ native delayed delivery

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureStorageQueues#301]
A regression bug was detected in the ASP build, https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/300, while it should have been caught in the ASQ build. We should figure out a way to test this using the in memory timeout manager, instead of the ASP one, in the ASQ ATT's

**Comment by danielmarbach** [comment]
Started some investigations today:

- `ConfigureEndpointAzureStorageQueueTransport` uses `transportConfig.DelayedDelivery().DisableTimeoutManager()` so just doing `EnableFeature<TimeoutManager>()` is not enough in the ATT
- It is possible to get access to IPersistTimeouts and then add a timeout data to the persister. Although I haven't figured out yet how the timeout data byte[] should actually look like. 

Need to do some more digging. Wondering if the effort is worth here though since the fix is already in place.

**Comment by yvesgoeleven** [comment]
Valid question. Think @andreasohlund mainly asked for this in order to prevent regression. But as @SeanFeldman already pointed out we have many gaps in the possible timeout persister vs native delivery permutations, so why not accept one more (or fix them all).

**Comment by bording** [comment]
Testing this is going to be tricky, which is why I didn't even try for the RabbitMQ transport.

Right now, each transport has to have specific logic to support the "hybrid" mode, but I want to move this feature into core, hopefully as part of the 7.1 release.

Based on that, I'm not sure if it's worth trying to find a way to test this at the transport level or not.

**Comment by SeanFeldman** [comment]
Trying to understand how the testing would work. @bording moving this into the core, how would it help with testing?

**Comment by bording** [comment]
@SeanFeldman If the support for the hybrid mode is in core and not the transports responsibility to implement, then core is where the tests would be. 

Acceptance tests might not be any easier to write, but core could have unit tests to verify that it works, which isn't really an option for the transports.

**Comment by SeanFeldman** [comment]
Decision was not to do anything at this point and address it again when Core has support for testing permutations  that would include hybrid mode.
