### ISSUE TITLE
Failing timeout message doesn't show in error queue

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#6]
## Who's Affected

Anyone who is using Timeouts with Azure Storage persistence

## Symptoms

Timeouts are executed regulary during long period of time and stop after the following exception

_EventName="MessageEvent" Message="Failed to process messageSystem.Data.Services.Client.DataServiceRequestException: An error occurred while processing this request. ---> System.Data.Services.Client.DataServiceClientException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. ---> System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)   --- End of inner exception stack trace ---   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)   at System.Net.TlsStream.Read(Byte[] buffer, Int32 offset, Int32 size)   at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)   at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)   --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.GetResponse()   at System.Data.Services.Client.HttpWebRequestMessage.GetResponse()   --- End of inner exception stack trace ---   --- End of inner exception stack trace ---   at System.Data.Services.Client.SaveResult.HandleResponse()   at System.Data.Services.Client.BaseSaveResult.EndRequest()   at System.Data.Services.Client.DataServiceContext.SaveChanges(SaveChangesOptions options)   at NServiceBus.Azure.TimeoutPersister.TryRemove(String timeoutId, TimeoutData& timeoutData) in y:\BuildAgent\work\ba77a0c29cee2af1\src\NServiceBus.Azure\Timeout\TimeoutLogic\TimeoutPersister.cs:line 179   at NServiceBus.Timeout.Hosting.Windows.TimeoutDispatcherProcessor.Handle(TransportMessage message) in c:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Timeout\Hosting\Windows\TimeoutDispatcherProcessor.cs:line 33   at NServiceBus.Satellites.SatelliteLauncher.HandleMessageReceived(Object sender, TransportMessageReceivedEventArgs e, ISatellite satellite) in c:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Satellites\SatelliteLauncher.cs:line 92   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg) in c:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 453   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in c:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 390   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in c:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 260   at NServiceBus.Azure.Transports.WindowsAzureStorageQueues.PollingDequeueStrategy.Action(Object obj) in y:\BuildAgent\work\ba77a0c29cee2af1\src\NServiceBus.Azure.Transports.WindowsAzureStorageQueues\PollingDequeueStrategy.cs:line 101" TraceSource="WaWorkerHost.exe"_

##Problem description

When `TimeoutPersister` is attempting to remove a successfully processed timeout data, it also supposed to return the next timeout data with `timeoutData` out arguent. `ServiceContext` is [saving changes](https://github.com/Particular/NServiceBus.Azure/blob/support-5.3/src/NServiceBus.Azure/Timeout/TimeoutLogic/TimeoutPersister.cs#L183) without retries using `context.SaveChanges()` which doesn't retry and if throws exceptions, causes that exception to bubble up and next timeout data not to be persisted. This in turn causes timeout not to be executed later at all.

Core is handling exception and sending it to the error queue. When persistence and transport are both using the same storage account, and persistence is not available, so is transport. That would explain why exception is not sent to the error queue. ~~When endpoing is running with self-hosted and NServiceBus.Host, endpoint is shutting down if we can't sent message to error queue. With Azure.Host it's not the case, endpoint is not been shut down since Azure fabric will start that endpoint automatically anyways. _That will cause **message to be lost**, endpoint to be running and timeout not to be executed._~~

## Possible solution

**Update**: `TimeoutPersister` was updated to [perform save with retries](https://github.com/Particular/NServiceBus.Azure/commit/c5a128e4602e731a29876469fcdebe1cf4384d2e)

**Based on MSDN documentation, this is what we'd need to do**
[`TableServiceContext` is obsoleted](https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.storage.table.dataservices.tableservicecontext.aspx). Instead `CloudTable` should be used and when `CloudTable.Execute()` is used, [`TableRequestOptions.RetryPolicy`](https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.storage.table.tablerequestoptions_members.aspx) one of the [retry policies](https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.storage.retrypolicies.aspx) could be applied (ex: [ExponentialRetry](https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.storage.retrypolicies.exponentialretry.exponentialretry.aspx).

**Original issue** reported on user group: [Random scheduler task randomly stops executing](https://groups.google.com/forum/#!topic/particularsoftware/MOv1g3wrwys)

**Comment by SeanFeldman** [comment]
@Particular/nservicebus please comment on the following:

It looks like core is not prepared to handle exceptions from [`TimeoutPersister.TryRemove()`](https://github.com/Particular/NServiceBus.Azure/blob/dd1f13bb8a7b7ad335d2d163c10e86444c191f75/src/NServiceBus.Azure/Timeout/TimeoutLogic/TimeoutPersister.cs#L143). Should persister handle it and if yes then what should we do about returned timeout data?

If old timeout data is not removed promptly, will it affect timeouts execution?

**Comment by danielmarbach** [comment]
Doesn't TryRemove imply that you should return false when you cannot remove it. So I'd say exceptions should be handled by the implementor

**Comment by SeanFeldman** [comment]
+1 @danielmarbach for pointing out that :)

We could use `SaveChangesWithRetries(SaveChangesOptions.ContinueOnError)` and see what [HTTP Status codes](https://msdn.microsoft.com/en-us/library/system.data.services.client.dataserviceresponse.aspx) are coming back, returning true or false based on that using similar logic to [HttpResponseMessage.IsSuccessStatusCode](https://msdn.microsoft.com/en-us/library/system.net.http.httpresponsemessage.issuccessstatuscode%28v=vs.118%29.aspx).

**Comment by andreasohlund** [comment]
Ifaik, tryremove should only return false if the TM wasn't found

https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs#L180

For other conditions you should bubble the ex up and let the retires handle then

**Comment by yvesgoeleven** [comment]
@andreasohlund we are bubbling up the exception right now, and as far as we can tell, that is the reason it stops the scheduler

**Comment by SeanFeldman** [comment]
Have tested today with @indualagarsamy core with NHibernate and ASQ. Core is handling exception and sending it to the error queue. My hypotheses is that persistence and transport are both using the same storage account, so when persistence is not available, so is transport. That would explain why exception is not sent to the error queue. Need confirmation from customer if that's the case and if endpoint is shutting down when it happens.

**Comment by Morlakh** [comment]
Hello,

The endpoint continues to run and other tasks continue to execute just fine. If you check the code excerpt I posted on user group (https://groups.google.com/d/msg/particularsoftware/MOv1g3wrwys/3ytzC_rqeUsJ) you'll see what I'm talking about. 

As for transport and persistence - yes, we use the same storage account for both. I assume that that's the culprit and we should split those to use separate storage accounts, shouldn't we?

**Comment by yvesgoeleven** [comment]
That could indeed be the case, it would be advised to separate the error queue storage account from the rest. It also strengthens the case to have a more durable backoff mechanism than retries only, but for cloudservices only storage would apply for such a mechanism as the disk should also not be considered durable (and even for vm's as those disk are actually in storage)

**Comment by SeanFeldman** [comment]
Hi @Morlakh,
Please note that if you use ServiceControl, both error queue and audit queue would need to be switched to the same storage account for SC to be able to function.

**Comment by SeanFeldman** [comment]
Updated the Problem description section in the [description](#problem-description) which explains why endpoint is running after failure to send a message to error queue (cc @indualagarsamy). There is a case of message loss.

**Comment by SeanFeldman** [comment]
@yvesgoeleven if error queue is separated into a different account, then audit queue needs to be on that account as well to ensure SC can have access to both.

**Comment by SeanFeldman** [comment]
@Morlakh do you run your endpoint in scaled out mode (ie more than one instance)?

**Comment by Morlakh** [comment]
Hey,

@SeanFeldman we run just one instance of the service.

I think I might have missed all these exceptions before, but this particular problem happened again on Sunday and it actually left the exception in the error queue (while the task stopped):

<code>
..."NServiceBus.ExceptionInfo.Reason":"ProcessingFailed","NServiceBus.ExceptionInfo.ExceptionType":"Microsoft.WindowsAzure.Storage.StorageException","NServiceBus.ExceptionInfo.InnerExceptionType":"System.Net.WebException","NServiceBus.ExceptionInfo.HelpLink":null,"NServiceBus.ExceptionInfo.Message":"The remote server returned an error: (503) Server Unavailable.","NServiceBus.ExceptionInfo.Source":"Microsoft.WindowsAzure.Storage","NServiceBus.ExceptionInfo.StackTrace":"   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)\r\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.DownloadRangeToStream(Stream target, Nullable`1 offset, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)\r\n   at NServiceBus.Azure.TimeoutPersister.Download(String stateAddress) in y:\\BuildAgent\\work\\ba77a0c29cee2af1\\src\\NServiceBus.Azure\\Timeout\\TimeoutLogic\\TimeoutPersister.cs:line 277\r\n   at NServiceBus.Azure.TimeoutPersister.TryRemove(String timeoutId, TimeoutData& timeoutData) in y:\\BuildAgent\\work\\ba77a0c29cee2af1\\src\\NServiceBus.Azure\\Timeout\\TimeoutLogic\\TimeoutPersister.cs:line 149\r\n   at NServiceBus.Timeout.Hosting.Windows.TimeoutDispatcherProcessor.Handle(TransportMessage message) in c:\\BuildAgent\\work\\31f8c64a6e8a2d7c\\src\\NServiceBus.Core\\Timeout\\Hosting\\Windows\\TimeoutDispatcherProcessor.cs:line 33\r\n   at NServiceBus.Satellites.SatelliteLauncher.HandleMessageReceived(Object sender, TransportMessageReceivedEventArgs e, ISatellite satellite) in c:\\BuildAgent\\work\\31f8c64a6e8a2d7c\\src\\NServiceBus.Core\\Satellites\\SatelliteLauncher.cs:line 92\r\n   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg) in c:\\BuildAgent\\work\\31f8c64a6e8a2d7c\\src\\NServiceBus.Core\\Unicast\\Transport\\TransportReceiver.cs:line 453   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in c:\\BuildAgent\\work\\31f8c64a6e8a2d7c\\src\\NServiceBus.Core\\Unicast\\Transport\\TransportReceiver.cs:line 390\r\n   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in c:\\BuildAgent\\work\\31f8c64a6e8a2d7c\\src\\NServiceBus.Core\\Unicast\\Transport\\TransportReceiver.cs:line 260\r\n   at NServiceBus.Azure.Transports.WindowsAzureStorageQueues.PollingDequeueStrategy.Action(Object obj) in y:\\BuildAgent\\work\\ba77a0c29cee2af1\\src\\NServiceBus.Azure.Transports.WindowsAzureStorageQueues\\PollingDequeueStrategy.cs:line 101","NServiceBus.FailedQ":"***","NServiceBus.TimeOfFailure":"2015-03-22 20:06:21:025512 Z"},"Body":"","CorrelationId":"326e98e4-5b50-427b-8285-a463014ac749","Recoverable":true}
</code>

We'll be separating transport and persistence accounts (as suggested by @yvesgoeleven) as soon as we find a free minute and, hopefully, this will eliminate the problem, since restarting/reimaging the service doesn't resume failed task.

**Comment by yvesgoeleven** [comment]
@Morlakh It definitly looks like you're being throttled by azure storage, separating transport from persistence account may indeed help. Another separation you could make, is the native cloud services logging, that one could also induce throttling on the account.

**Comment by SeanFeldman** [comment]
Addressed by https://github.com/Particular/NServiceBus.Azure/commit/c5a128e4602e731a29876469fcdebe1cf4384d2e
